# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created: Tue Jun 13 04:10:56 2017
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_FieldTool(object):
    def setupUi(self, FieldTool):
        FieldTool.setObjectName("FieldTool")
        FieldTool.resize(725, 425)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FieldTool.sizePolicy().hasHeightForWidth())
        FieldTool.setSizePolicy(sizePolicy)
        FieldTool.setMinimumSize(QtCore.QSize(750, 475))
        FieldTool.setMaximumSize(QtCore.QSize(1080, 1080))
        self.centralwidget = QtGui.QWidget(FieldTool)
        self.centralwidget.setObjectName("centralwidget")
        FieldTool.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(FieldTool)
        self.statusbar.setObjectName("statusbar")
        FieldTool.setStatusBar(self.statusbar)
        self.dockWidget_10 = QtGui.QDockWidget(FieldTool)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget_10.sizePolicy().hasHeightForWidth())
        self.dockWidget_10.setSizePolicy(sizePolicy)
        self.dockWidget_10.setMinimumSize(QtCore.QSize(360, 425))
        self.dockWidget_10.setObjectName("dockWidget_10")
        self.dockWidget_10.setWindowTitle("Field Tool Visual Buffer")
        self.dockWidgetContents_10 = QtGui.QWidget()
        self.dockWidgetContents_10.setObjectName("dockWidgetContents_10")
        self.gridLayout_13 = QtGui.QGridLayout(self.dockWidgetContents_10)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.imageButton = QtGui.QPushButton(self.dockWidgetContents_10)
        self.imageButton.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.imageButton.sizePolicy().hasHeightForWidth())
        self.imageButton.setSizePolicy(sizePolicy)
        self.imageButton.setMinimumSize(QtCore.QSize(275, 275))
        self.imageButton.setMaximumSize(QtCore.QSize(1080, 1080))
        self.imageButton.setCursor(QtCore.Qt.CrossCursor)
        self.imageButton.setAutoFillBackground(True)
        self.imageButton.setText("")
        self.imageButton.setIconSize(QtCore.QSize(720, 720))
        self.imageButton.setCheckable(False)
        self.imageButton.setAutoDefault(False)
        self.imageButton.setFlat(False)
        self.imageButton.setObjectName("imageButton")        
        self.gridLayout_13.addWidget(self.imageButton, 0, 0, 1, 1)
        self.switch3DButton = QtGui.QPushButton(self.dockWidgetContents_10)
        self.switch3DButton.setEnabled(False)
        self.switch3DButton.setObjectName("switch3DButton")
        self.gridLayout_13.addWidget(self.switch3DButton, 2, 0, 1, 1)
        self.slider3D = QtGui.QSlider(self.dockWidgetContents_10)
        self.slider3D.setMaximum(20)
        self.slider3D.setProperty("value", 10)
        self.slider3D.setOrientation(QtCore.Qt.Horizontal)
        self.slider3D.setInvertedAppearance(False)
        self.slider3D.setObjectName("slider3D")
        self.gridLayout_13.addWidget(self.slider3D, 1, 0, 1, 1)
        self.dockWidget_10.setWidget(self.dockWidgetContents_10)
        FieldTool.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.dockWidget_10)
        self.dockWidget_12 = QtGui.QDockWidget(FieldTool)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget_12.sizePolicy().hasHeightForWidth())
        self.dockWidget_12.setSizePolicy(sizePolicy)
        self.dockWidget_12.setMinimumSize(QtCore.QSize(374, 425))
        self.dockWidget_12.setObjectName("dockWidget_12")
        self.dockWidget_12.setWindowTitle("Field Tool Settings")
        self.dockWidgetContents_12 = QtGui.QWidget()
        self.dockWidgetContents_12.setObjectName("dockWidgetContents_12")
        self.verticalLayout = QtGui.QVBoxLayout(self.dockWidgetContents_12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(self.dockWidgetContents_12)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(350, 330))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_10 = QtGui.QGridLayout(self.tab)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.scrollArea = QtGui.QScrollArea(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(325, 200))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -297, 313, 704))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.farmPosition = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.farmPosition.sizePolicy().hasHeightForWidth())
        self.farmPosition.setSizePolicy(sizePolicy)
        self.farmPosition.setMinimumSize(QtCore.QSize(200, 315))
        self.farmPosition.setMaximumSize(QtCore.QSize(16777215, 315))
        self.farmPosition.setCheckable(True)
        self.farmPosition.setChecked(False)
        self.farmPosition.setObjectName("farmPosition")
        self.gridLayout_4 = QtGui.QGridLayout(self.farmPosition)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.farmTranslateLayout = QtGui.QWidget(self.farmPosition)
        self.farmTranslateLayout.setMinimumSize(QtCore.QSize(0, 30))
        self.farmTranslateLayout.setMaximumSize(QtCore.QSize(16777215, 30))
        self.farmTranslateLayout.setObjectName("farmTranslateLayout")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.farmTranslateLayout)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_8 = QtGui.QLabel(self.farmTranslateLayout)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(50, 0))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_10.addWidget(self.label_8)
        self.translateXBox = QtGui.QDoubleSpinBox(self.farmTranslateLayout)
        self.translateXBox.setMinimumSize(QtCore.QSize(48, 0))
        self.translateXBox.setFrame(True)
        self.translateXBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.translateXBox.setDecimals(3)
        self.translateXBox.setMinimum(-99.99)
        self.translateXBox.setObjectName("translateXBox")
        self.horizontalLayout_10.addWidget(self.translateXBox)
        self.translateYBox = QtGui.QDoubleSpinBox(self.farmTranslateLayout)
        self.translateYBox.setMinimumSize(QtCore.QSize(48, 0))
        self.translateYBox.setFrame(True)
        self.translateYBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.translateYBox.setDecimals(3)
        self.translateYBox.setMinimum(-99.9)
        self.translateYBox.setObjectName("translateYBox")
        self.horizontalLayout_10.addWidget(self.translateYBox)
        self.translateZBox = QtGui.QDoubleSpinBox(self.farmTranslateLayout)
        self.translateZBox.setMinimumSize(QtCore.QSize(48, 0))
        self.translateZBox.setFrame(True)
        self.translateZBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.translateZBox.setDecimals(3)
        self.translateZBox.setMinimum(-99.99)
        self.translateZBox.setObjectName("translateZBox")
        self.horizontalLayout_10.addWidget(self.translateZBox)
        self.gridLayout_2.addWidget(self.farmTranslateLayout, 0, 0, 1, 1)
        self.farmMeshLayout = QtGui.QWidget(self.farmPosition)
        self.farmMeshLayout.setMinimumSize(QtCore.QSize(0, 35))
        self.farmMeshLayout.setMaximumSize(QtCore.QSize(16777215, 35))
        self.farmMeshLayout.setObjectName("farmMeshLayout")
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.farmMeshLayout)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_9 = QtGui.QLabel(self.farmMeshLayout)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(40, 0))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_11.addWidget(self.label_9)
        self.farmMeshLine = QtGui.QLineEdit(self.farmMeshLayout)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.farmMeshLine.sizePolicy().hasHeightForWidth())
        self.farmMeshLine.setSizePolicy(sizePolicy)
        self.farmMeshLine.setMinimumSize(QtCore.QSize(25, 0))
        self.farmMeshLine.setObjectName("farmMeshLine")
        self.horizontalLayout_11.addWidget(self.farmMeshLine)
        self.farmMeshButton = QtGui.QPushButton(self.farmMeshLayout)
        self.farmMeshButton.setMinimumSize(QtCore.QSize(10, 0))
        self.farmMeshButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/local/vince/maya/projects/MattTraynar_demo/scripts/FieldTool/Images/browseFolder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.farmMeshButton.setIcon(icon)
        self.farmMeshButton.setIconSize(QtCore.QSize(25, 25))
        self.farmMeshButton.setCheckable(False)
        self.farmMeshButton.setAutoDefault(False)
        self.farmMeshButton.setDefault(False)
        self.farmMeshButton.setFlat(True)
        self.farmMeshButton.setObjectName("farmMeshButton")
        self.horizontalLayout_11.addWidget(self.farmMeshButton)
        self.gridLayout_2.addWidget(self.farmMeshLayout, 1, 0, 1, 1)
        self.farmMeshBrowser = QtGui.QPlainTextEdit(self.farmPosition)
        self.farmMeshBrowser.setReadOnly(True)
        self.farmMeshBrowser.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.farmMeshBrowser.setObjectName("farmMeshBrowser")
        self.gridLayout_2.addWidget(self.farmMeshBrowser, 2, 0, 1, 1)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.liveUpdateButton = QtGui.QPushButton(self.farmPosition)
        self.liveUpdateButton.setMinimumSize(QtCore.QSize(120, 40))
        self.liveUpdateButton.setMaximumSize(QtCore.QSize(120, 40))
        self.liveUpdateButton.setObjectName("liveUpdateButton")
        self.verticalLayout_4.addWidget(self.liveUpdateButton)
        self.acceptButton = QtGui.QPushButton(self.farmPosition)
        self.acceptButton.setEnabled(False)
        self.acceptButton.setMinimumSize(QtCore.QSize(120, 40))
        self.acceptButton.setMaximumSize(QtCore.QSize(120, 40))
        self.acceptButton.setObjectName("acceptButton")
        self.verticalLayout_4.addWidget(self.acceptButton)
        self.horizontalLayout_25.addLayout(self.verticalLayout_4)
        self.liveUpdateProgress = QtGui.QProgressBar(self.farmPosition)
        self.liveUpdateProgress.setEnabled(False)
        self.liveUpdateProgress.setMinimumSize(QtCore.QSize(100, 80))
        self.liveUpdateProgress.setMaximumSize(QtCore.QSize(16777215, 84))
        self.liveUpdateProgress.setProperty("value", 0)
        self.liveUpdateProgress.setTextVisible(False)
        self.liveUpdateProgress.setOrientation(QtCore.Qt.Vertical)
        self.liveUpdateProgress.setObjectName("liveUpdateProgress")
        self.horizontalLayout_25.addWidget(self.liveUpdateProgress)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout_25, 3, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.farmPosition, 5, 0, 1, 1)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_7.addWidget(self.label_3, 0, 0, 1, 1)
        self.startPointSizeBox = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startPointSizeBox.sizePolicy().hasHeightForWidth())
        self.startPointSizeBox.setSizePolicy(sizePolicy)
        self.startPointSizeBox.setMinimumSize(QtCore.QSize(60, 0))
        self.startPointSizeBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.startPointSizeBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.startPointSizeBox.setMinimum(1)
        self.startPointSizeBox.setMaximum(100)
        self.startPointSizeBox.setProperty("value", 6)
        self.startPointSizeBox.setObjectName("startPointSizeBox")
        self.gridLayout_7.addWidget(self.startPointSizeBox, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_7, 2, 0, 1, 1)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_8.addWidget(self.label_4, 0, 0, 1, 1)
        self.terrainSizeBox = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.terrainSizeBox.sizePolicy().hasHeightForWidth())
        self.terrainSizeBox.setSizePolicy(sizePolicy)
        self.terrainSizeBox.setMinimumSize(QtCore.QSize(60, 0))
        self.terrainSizeBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.terrainSizeBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.terrainSizeBox.setMinimum(1)
        self.terrainSizeBox.setMaximum(100)
        self.terrainSizeBox.setProperty("value", 50)
        self.terrainSizeBox.setObjectName("terrainSizeBox")
        self.gridLayout_8.addWidget(self.terrainSizeBox, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_8, 1, 0, 1, 1)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(100, 0))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 0, 0, 1, 1)
        self.roughnessBox = QtGui.QDoubleSpinBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.roughnessBox.sizePolicy().hasHeightForWidth())
        self.roughnessBox.setSizePolicy(sizePolicy)
        self.roughnessBox.setMinimumSize(QtCore.QSize(60, 0))
        self.roughnessBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.roughnessBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.roughnessBox.setDecimals(3)
        self.roughnessBox.setSingleStep(0.1)
        self.roughnessBox.setProperty("value", 12.0)
        self.roughnessBox.setObjectName("roughnessBox")
        self.gridLayout_6.addWidget(self.roughnessBox, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_6, 3, 0, 1, 1)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.seedValueCheck = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.seedValueCheck.setMinimumSize(QtCore.QSize(0, 0))
        self.seedValueCheck.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.seedValueCheck.setIconSize(QtCore.QSize(16, 16))
        self.seedValueCheck.setObjectName("seedValueCheck")
        self.gridLayout_9.addWidget(self.seedValueCheck, 0, 0, 1, 1)
        self.seedValueBox = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.seedValueBox.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seedValueBox.sizePolicy().hasHeightForWidth())
        self.seedValueBox.setSizePolicy(sizePolicy)
        self.seedValueBox.setMinimumSize(QtCore.QSize(60, 0))
        self.seedValueBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.seedValueBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.seedValueBox.setMaximum(999999999)
        self.seedValueBox.setObjectName("seedValueBox")
        self.gridLayout_9.addWidget(self.seedValueBox, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_7 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(100, 0))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 0, 0, 1, 1)
        self.heightmapIterationsBox = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heightmapIterationsBox.sizePolicy().hasHeightForWidth())
        self.heightmapIterationsBox.setSizePolicy(sizePolicy)
        self.heightmapIterationsBox.setMinimumSize(QtCore.QSize(60, 0))
        self.heightmapIterationsBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.heightmapIterationsBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.heightmapIterationsBox.setMinimum(1)
        self.heightmapIterationsBox.setProperty("value", 6)
        self.heightmapIterationsBox.setObjectName("heightmapIterationsBox")
        self.gridLayout_5.addWidget(self.heightmapIterationsBox, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 4, 0, 1, 1)
        self.trees = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trees.sizePolicy().hasHeightForWidth())
        self.trees.setSizePolicy(sizePolicy)
        self.trees.setMinimumSize(QtCore.QSize(0, 225))
        self.trees.setMaximumSize(QtCore.QSize(16777215, 225))
        self.trees.setCheckable(True)
        self.trees.setChecked(False)
        self.trees.setObjectName("trees")
        self.gridLayout_3 = QtGui.QGridLayout(self.trees)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.clusterTreesLayout = QtGui.QWidget(self.trees)
        self.clusterTreesLayout.setMaximumSize(QtCore.QSize(16777215, 30))
        self.clusterTreesLayout.setObjectName("clusterTreesLayout")
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.clusterTreesLayout)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.normalTreesCheck = QtGui.QCheckBox(self.clusterTreesLayout)
        self.normalTreesCheck.setChecked(True)
        self.normalTreesCheck.setObjectName("normalTreesCheck")
        self.horizontalLayout_13.addWidget(self.normalTreesCheck)
        self.clusterTreesCheck = QtGui.QCheckBox(self.clusterTreesLayout)
        self.clusterTreesCheck.setMinimumSize(QtCore.QSize(0, 20))
        self.clusterTreesCheck.setChecked(True)
        self.clusterTreesCheck.setObjectName("clusterTreesCheck")
        self.horizontalLayout_13.addWidget(self.clusterTreesCheck)
        self.gridLayout_3.addWidget(self.clusterTreesLayout, 0, 0, 1, 1)
        self.TreeMeshLayout = QtGui.QWidget(self.trees)
        self.TreeMeshLayout.setMinimumSize(QtCore.QSize(0, 35))
        self.TreeMeshLayout.setMaximumSize(QtCore.QSize(16777215, 35))
        self.TreeMeshLayout.setObjectName("TreeMeshLayout")
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.TreeMeshLayout)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_10 = QtGui.QLabel(self.TreeMeshLayout)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMinimumSize(QtCore.QSize(10, 0))
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_12.addWidget(self.label_10)
        self.treeMeshLine = QtGui.QLineEdit(self.TreeMeshLayout)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeMeshLine.sizePolicy().hasHeightForWidth())
        self.treeMeshLine.setSizePolicy(sizePolicy)
        self.treeMeshLine.setMinimumSize(QtCore.QSize(100, 0))
        self.treeMeshLine.setObjectName("treeMeshLine")
        self.horizontalLayout_12.addWidget(self.treeMeshLine)
        self.treeMeshButton = QtGui.QPushButton(self.TreeMeshLayout)
        self.treeMeshButton.setMinimumSize(QtCore.QSize(10, 0))
        self.treeMeshButton.setText("")
        self.treeMeshButton.setIcon(icon)
        self.treeMeshButton.setIconSize(QtCore.QSize(25, 25))
        self.treeMeshButton.setCheckable(False)
        self.treeMeshButton.setAutoDefault(False)
        self.treeMeshButton.setDefault(False)
        self.treeMeshButton.setFlat(True)
        self.treeMeshButton.setObjectName("treeMeshButton")
        self.horizontalLayout_12.addWidget(self.treeMeshButton)
        self.gridLayout_3.addWidget(self.TreeMeshLayout, 1, 0, 1, 1)
        self.treeMeshBrowser = QtGui.QPlainTextEdit(self.trees)
        self.treeMeshBrowser.setReadOnly(True)
        self.treeMeshBrowser.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.treeMeshBrowser.setObjectName("treeMeshBrowser")
        self.gridLayout_3.addWidget(self.treeMeshBrowser, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.trees, 6, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_10.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_14 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.scrollArea_3 = QtGui.QScrollArea(self.tab_2)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, -428, 313, 739))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_15 = QtGui.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.groupBox_2 = QtGui.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_2.setMinimumSize(QtCore.QSize(250, 120))
        self.groupBox_2.setMaximumSize(QtCore.QSize(300, 120))
        self.groupBox_2.setCheckable(True)
        self.groupBox_2.setChecked(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_19 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.TextureLayout_2 = QtGui.QWidget(self.groupBox_2)
        self.TextureLayout_2.setMinimumSize(QtCore.QSize(0, 30))
        self.TextureLayout_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.TextureLayout_2.setObjectName("TextureLayout_2")
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.TextureLayout_2)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_14 = QtGui.QLabel(self.TextureLayout_2)
        self.label_14.setMinimumSize(QtCore.QSize(0, 20))
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_15.addWidget(self.label_14)
        self.textureLine = QtGui.QLineEdit(self.TextureLayout_2)
        self.textureLine.setMinimumSize(QtCore.QSize(0, 20))
        self.textureLine.setMaximumSize(QtCore.QSize(16777215, 20))
        self.textureLine.setObjectName("textureLine")
        self.horizontalLayout_15.addWidget(self.textureLine)
        self.textureButton = QtGui.QPushButton(self.TextureLayout_2)
        self.textureButton.setMinimumSize(QtCore.QSize(0, 20))
        self.textureButton.setMaximumSize(QtCore.QSize(16777215, 20))
        self.textureButton.setText("")
        self.textureButton.setIcon(icon)
        self.textureButton.setIconSize(QtCore.QSize(25, 25))
        self.textureButton.setFlat(True)
        self.textureButton.setObjectName("textureButton")
        self.horizontalLayout_15.addWidget(self.textureButton)
        self.verticalLayout_10.addWidget(self.TextureLayout_2)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem2)
        self.loadTextureButton = QtGui.QPushButton(self.groupBox_2)
        self.loadTextureButton.setEnabled(False)
        self.loadTextureButton.setObjectName("loadTextureButton")
        self.horizontalLayout_21.addWidget(self.loadTextureButton)
        self.postGenTexture = QtGui.QPushButton(self.groupBox_2)
        self.postGenTexture.setEnabled(False)
        self.postGenTexture.setObjectName("postGenTexture")
        self.horizontalLayout_21.addWidget(self.postGenTexture)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem3)
        self.verticalLayout_10.addLayout(self.horizontalLayout_21)
        self.gridLayout_19.addLayout(self.verticalLayout_10, 0, 0, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox_2, 7, 0, 1, 2)
        self.gridLayout_17 = QtGui.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_11 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_17.addWidget(self.label_11, 0, 0, 1, 1)
        self.userTerrainLine = QtGui.QLineEdit(self.scrollAreaWidgetContents_3)
        self.userTerrainLine.setObjectName("userTerrainLine")
        self.gridLayout_17.addWidget(self.userTerrainLine, 0, 1, 1, 1)
        self.userTerrainButton = QtGui.QPushButton(self.scrollAreaWidgetContents_3)
        self.userTerrainButton.setText("")
        self.userTerrainButton.setIcon(icon)
        self.userTerrainButton.setIconSize(QtCore.QSize(25, 25))
        self.userTerrainButton.setFlat(True)
        self.userTerrainButton.setObjectName("userTerrainButton")
        self.gridLayout_17.addWidget(self.userTerrainButton, 0, 2, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_17, 2, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_3.setMinimumSize(QtCore.QSize(250, 120))
        self.groupBox_3.setMaximumSize(QtCore.QSize(300, 120))
        self.groupBox_3.setCheckable(True)
        self.groupBox_3.setChecked(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_20 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.TextureLayout_3 = QtGui.QWidget(self.groupBox_3)
        self.TextureLayout_3.setMinimumSize(QtCore.QSize(0, 30))
        self.TextureLayout_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.TextureLayout_3.setObjectName("TextureLayout_3")
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.TextureLayout_3)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_15 = QtGui.QLabel(self.TextureLayout_3)
        self.label_15.setMinimumSize(QtCore.QSize(0, 20))
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_16.addWidget(self.label_15)
        self.heightmapLine = QtGui.QLineEdit(self.TextureLayout_3)
        self.heightmapLine.setMinimumSize(QtCore.QSize(0, 20))
        self.heightmapLine.setMaximumSize(QtCore.QSize(16777215, 20))
        self.heightmapLine.setObjectName("heightmapLine")
        self.horizontalLayout_16.addWidget(self.heightmapLine)
        self.heightmapButton = QtGui.QPushButton(self.TextureLayout_3)
        self.heightmapButton.setMinimumSize(QtCore.QSize(0, 20))
        self.heightmapButton.setMaximumSize(QtCore.QSize(16777215, 20))
        self.heightmapButton.setText("")
        self.heightmapButton.setIcon(icon)
        self.heightmapButton.setIconSize(QtCore.QSize(25, 25))
        self.heightmapButton.setFlat(True)
        self.heightmapButton.setObjectName("heightmapButton")
        self.horizontalLayout_16.addWidget(self.heightmapButton)
        self.verticalLayout_12.addWidget(self.TextureLayout_3)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem4)
        self.loadHeightmapButton = QtGui.QPushButton(self.groupBox_3)
        self.loadHeightmapButton.setEnabled(False)
        self.loadHeightmapButton.setObjectName("loadHeightmapButton")
        self.horizontalLayout_22.addWidget(self.loadHeightmapButton)
        self.postGenHeightmap = QtGui.QPushButton(self.groupBox_3)
        self.postGenHeightmap.setEnabled(False)
        self.postGenHeightmap.setObjectName("postGenHeightmap")
        self.horizontalLayout_22.addWidget(self.postGenHeightmap)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem5)
        self.verticalLayout_12.addLayout(self.horizontalLayout_22)
        self.gridLayout_20.addLayout(self.verticalLayout_12, 0, 0, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox_3, 9, 0, 1, 2)
        self.gridLayout_16 = QtGui.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_2 = QtGui.QLabel(self.scrollAreaWidgetContents_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout_16.addWidget(self.label_2, 0, 0, 1, 1)
        self.defaultLine = QtGui.QLineEdit(self.scrollAreaWidgetContents_3)
        self.defaultLine.setObjectName("defaultLine")
        self.gridLayout_16.addWidget(self.defaultLine, 0, 1, 1, 1)
        self.defaultButton = QtGui.QPushButton(self.scrollAreaWidgetContents_3)
        self.defaultButton.setText("")
        self.defaultButton.setIcon(icon)
        self.defaultButton.setIconSize(QtCore.QSize(25, 25))
        self.defaultButton.setFlat(True)
        self.defaultButton.setObjectName("defaultButton")
        self.gridLayout_16.addWidget(self.defaultButton, 0, 2, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_16, 0, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_5.setEnabled(False)
        self.groupBox_5.setMinimumSize(QtCore.QSize(250, 60))
        self.groupBox_5.setMaximumSize(QtCore.QSize(300, 60))
        self.groupBox_5.setCheckable(True)
        self.groupBox_5.setChecked(False)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_23 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.TextureLayout_7 = QtGui.QWidget(self.groupBox_5)
        self.TextureLayout_7.setMinimumSize(QtCore.QSize(0, 30))
        self.TextureLayout_7.setMaximumSize(QtCore.QSize(16777215, 20))
        self.TextureLayout_7.setObjectName("TextureLayout_7")
        self.horizontalLayout_31 = QtGui.QHBoxLayout(self.TextureLayout_7)
        self.horizontalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.label_19 = QtGui.QLabel(self.TextureLayout_7)
        self.label_19.setMinimumSize(QtCore.QSize(0, 20))
        self.label_19.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_31.addWidget(self.label_19)
        self.locationLine = QtGui.QLineEdit(self.TextureLayout_7)
        self.locationLine.setMinimumSize(QtCore.QSize(0, 20))
        self.locationLine.setMaximumSize(QtCore.QSize(16777215, 20))
        self.locationLine.setObjectName("locationLine")
        self.horizontalLayout_31.addWidget(self.locationLine)
        self.locationButton = QtGui.QPushButton(self.TextureLayout_7)
        self.locationButton.setMinimumSize(QtCore.QSize(0, 20))
        self.locationButton.setMaximumSize(QtCore.QSize(16777215, 20))
        self.locationButton.setText("")
        self.locationButton.setIcon(icon)
        self.locationButton.setIconSize(QtCore.QSize(25, 25))
        self.locationButton.setFlat(True)
        self.locationButton.setObjectName("locationButton")
        self.horizontalLayout_31.addWidget(self.locationButton)
        self.gridLayout_23.addWidget(self.TextureLayout_7, 0, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_23.addItem(spacerItem6, 1, 0, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox_5, 11, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox.setEnabled(True)
        self.groupBox.setMinimumSize(QtCore.QSize(250, 90))
        self.groupBox.setMaximumSize(QtCore.QSize(300, 90))
        self.groupBox.setCheckable(True)
        self.groupBox.setChecked(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_18 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_7.addWidget(self.label_12)
        self.terrainLine = QtGui.QLineEdit(self.groupBox)
        self.terrainLine.setObjectName("terrainLine")
        self.horizontalLayout_7.addWidget(self.terrainLine)
        self.terrainButton = QtGui.QPushButton(self.groupBox)
        self.terrainButton.setMinimumSize(QtCore.QSize(0, 20))
        self.terrainButton.setText("")
        self.terrainButton.setIcon(icon)
        self.terrainButton.setIconSize(QtCore.QSize(25, 25))
        self.terrainButton.setFlat(True)
        self.terrainButton.setObjectName("terrainButton")
        self.horizontalLayout_7.addWidget(self.terrainButton)
        self.verticalLayout_15.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.triangulateCheck = QtGui.QCheckBox(self.groupBox)
        self.triangulateCheck.setObjectName("triangulateCheck")
        self.horizontalLayout_27.addWidget(self.triangulateCheck)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem7)
        self.postGenTerrain = QtGui.QPushButton(self.groupBox)
        self.postGenTerrain.setEnabled(False)
        self.postGenTerrain.setObjectName("postGenTerrain")
        self.horizontalLayout_27.addWidget(self.postGenTerrain)
        self.verticalLayout_15.addLayout(self.horizontalLayout_27)
        self.gridLayout_18.addLayout(self.verticalLayout_15, 0, 0, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox, 4, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_4.setMinimumSize(QtCore.QSize(250, 120))
        self.groupBox_4.setMaximumSize(QtCore.QSize(300, 120))
        self.groupBox_4.setCheckable(True)
        self.groupBox_4.setChecked(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_21 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.TextureLayout_6 = QtGui.QWidget(self.groupBox_4)
        self.TextureLayout_6.setMinimumSize(QtCore.QSize(0, 30))
        self.TextureLayout_6.setMaximumSize(QtCore.QSize(16777215, 20))
        self.TextureLayout_6.setObjectName("TextureLayout_6")
        self.horizontalLayout_19 = QtGui.QHBoxLayout(self.TextureLayout_6)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_18 = QtGui.QLabel(self.TextureLayout_6)
        self.label_18.setMinimumSize(QtCore.QSize(0, 20))
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_19.addWidget(self.label_18)
        self.wallsLine = QtGui.QLineEdit(self.TextureLayout_6)
        self.wallsLine.setMinimumSize(QtCore.QSize(0, 20))
        self.wallsLine.setMaximumSize(QtCore.QSize(16777215, 20))
        self.wallsLine.setObjectName("wallsLine")
        self.horizontalLayout_19.addWidget(self.wallsLine)
        self.wallsButton = QtGui.QPushButton(self.TextureLayout_6)
        self.wallsButton.setMinimumSize(QtCore.QSize(0, 20))
        self.wallsButton.setMaximumSize(QtCore.QSize(16777215, 20))
        self.wallsButton.setText("")
        self.wallsButton.setIcon(icon)
        self.wallsButton.setIconSize(QtCore.QSize(25, 25))
        self.wallsButton.setFlat(True)
        self.wallsButton.setObjectName("wallsButton")
        self.horizontalLayout_19.addWidget(self.wallsButton)
        self.verticalLayout_14.addWidget(self.TextureLayout_6)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem8)
        self.loadWallsButton = QtGui.QPushButton(self.groupBox_4)
        self.loadWallsButton.setEnabled(False)
        self.loadWallsButton.setObjectName("loadWallsButton")
        self.horizontalLayout_30.addWidget(self.loadWallsButton)
        self.postGenWalls = QtGui.QPushButton(self.groupBox_4)
        self.postGenWalls.setEnabled(False)
        self.postGenWalls.setObjectName("postGenWalls")
        self.horizontalLayout_30.addWidget(self.postGenWalls)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem9)
        self.verticalLayout_14.addLayout(self.horizontalLayout_30)
        self.gridLayout_21.addLayout(self.verticalLayout_14, 0, 0, 1, 1)
        self.gridLayout_15.addWidget(self.groupBox_4, 10, 0, 1, 1)
        self.gridLayout_22 = QtGui.QGridLayout()
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.horizontalLayout_32 = QtGui.QHBoxLayout()
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        spacerItem10 = QtGui.QSpacerItem(58, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem10)
        self.generateButton = QtGui.QPushButton(self.scrollAreaWidgetContents_3)
        self.generateButton.setMinimumSize(QtCore.QSize(75, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.generateButton.setFont(font)
        self.generateButton.setObjectName("generateButton")
        self.horizontalLayout_32.addWidget(self.generateButton)
        spacerItem11 = QtGui.QSpacerItem(58, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_32.addItem(spacerItem11)
        self.gridLayout_22.addLayout(self.horizontalLayout_32, 0, 0, 1, 1)
        self.generateProgress = QtGui.QProgressBar(self.scrollAreaWidgetContents_3)
        self.generateProgress.setEnabled(False)
        self.generateProgress.setProperty("value", 0)
        self.generateProgress.setAlignment(QtCore.Qt.AlignCenter)
        self.generateProgress.setTextVisible(True)
        self.generateProgress.setObjectName("generateProgress")
        self.gridLayout_22.addWidget(self.generateProgress, 1, 0, 1, 1)
        self.horizontalLayout_33 = QtGui.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        spacerItem12 = QtGui.QSpacerItem(58, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem12)
        self.importButton = QtGui.QPushButton(self.scrollAreaWidgetContents_3)
        self.importButton.setEnabled(False)
        self.importButton.setMinimumSize(QtCore.QSize(75, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.importButton.setFont(font)
        self.importButton.setObjectName("importButton")
        self.horizontalLayout_33.addWidget(self.importButton)
        spacerItem13 = QtGui.QSpacerItem(58, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem13)
        self.gridLayout_22.addLayout(self.horizontalLayout_33, 2, 0, 1, 1)
        self.gridLayout_15.addLayout(self.gridLayout_22, 12, 0, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_14.addWidget(self.scrollArea_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_11 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.scrollArea_2 = QtGui.QScrollArea(self.tab_3)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 330, 311))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_12 = QtGui.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.pushButton = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton.setText("")
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(25, 25))
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.loadSettingsButton = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        self.loadSettingsButton.setEnabled(True)
        self.loadSettingsButton.setObjectName("loadSettingsButton")
        self.horizontalLayout_2.addWidget(self.loadSettingsButton)
        self.gridLayout_12.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_2 = QtGui.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.pushButton_2 = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_2.setText("")
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.saveSettingsButton = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        self.saveSettingsButton.setEnabled(False)
        self.saveSettingsButton.setObjectName("saveSettingsButton")
        self.horizontalLayout_3.addWidget(self.saveSettingsButton)
        self.gridLayout_12.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem14)
        self.resetSettingsButton = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        self.resetSettingsButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resetSettingsButton.sizePolicy().hasHeightForWidth())
        self.resetSettingsButton.setSizePolicy(sizePolicy)
        self.resetSettingsButton.setAutoFillBackground(False)
        self.resetSettingsButton.setAutoDefault(True)
        self.resetSettingsButton.setDefault(False)
        self.resetSettingsButton.setFlat(False)
        self.resetSettingsButton.setObjectName("resetSettingsButton")
        self.horizontalLayout_4.addWidget(self.resetSettingsButton)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem15)
        self.gridLayout_12.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_11.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.dockWidget_12.setWidget(self.dockWidgetContents_12)
        FieldTool.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.dockWidget_12)

        self.retranslateUi(FieldTool)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(FieldTool)

    def retranslateUi(self, FieldTool):
        FieldTool.setWindowTitle(QtGui.QApplication.translate("FieldTool", "Field Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.switch3DButton.setText(QtGui.QApplication.translate("FieldTool", "Switch to 3D", None, QtGui.QApplication.UnicodeUTF8))
        self.farmPosition.setTitle(QtGui.QApplication.translate("FieldTool", "Farm Position", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("FieldTool", "Translate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("FieldTool", "Meshes", None, QtGui.QApplication.UnicodeUTF8))
        self.liveUpdateButton.setText(QtGui.QApplication.translate("FieldTool", "Live Update On", None, QtGui.QApplication.UnicodeUTF8))
        self.acceptButton.setText(QtGui.QApplication.translate("FieldTool", "Accept and Continue", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("FieldTool", "Start Point Size", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("FieldTool", "Terrain Size", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("FieldTool", "Roughness Value", None, QtGui.QApplication.UnicodeUTF8))
        self.seedValueCheck.setText(QtGui.QApplication.translate("FieldTool", "Seed Value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("FieldTool", "Heightmap Iterations", None, QtGui.QApplication.UnicodeUTF8))
        self.trees.setTitle(QtGui.QApplication.translate("FieldTool", "Trees", None, QtGui.QApplication.UnicodeUTF8))
        self.normalTreesCheck.setText(QtGui.QApplication.translate("FieldTool", "Normal Trees", None, QtGui.QApplication.UnicodeUTF8))
        self.clusterTreesCheck.setText(QtGui.QApplication.translate("FieldTool", "Cluster Trees", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("FieldTool", "Tree Meshes", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("FieldTool", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("FieldTool", "Export Texture", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("FieldTool", "Export Location", None, QtGui.QApplication.UnicodeUTF8))
        self.loadTextureButton.setText(QtGui.QApplication.translate("FieldTool", "Load Texture to Window", None, QtGui.QApplication.UnicodeUTF8))
        self.postGenTexture.setText(QtGui.QApplication.translate("FieldTool", "Post-Gen Export", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("FieldTool", "User Terrain", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("FieldTool", "Export Heightmap", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("FieldTool", "Export Location", None, QtGui.QApplication.UnicodeUTF8))
        self.loadHeightmapButton.setText(QtGui.QApplication.translate("FieldTool", "Load Heightmap to Window", None, QtGui.QApplication.UnicodeUTF8))
        self.postGenHeightmap.setText(QtGui.QApplication.translate("FieldTool", "Post-Gen Export", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("FieldTool", "Set Default", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("FieldTool", "Export Tree/Farm Position", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("FieldTool", "Export Location", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("FieldTool", "Export Terrain", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("FieldTool", "Export Location", None, QtGui.QApplication.UnicodeUTF8))
        self.triangulateCheck.setText(QtGui.QApplication.translate("FieldTool", "Triangulate Mesh", None, QtGui.QApplication.UnicodeUTF8))
        self.postGenTerrain.setText(QtGui.QApplication.translate("FieldTool", "Post-Gen Export", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("FieldTool", "Export Walls", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("FieldTool", "Export Location", None, QtGui.QApplication.UnicodeUTF8))
        self.loadWallsButton.setText(QtGui.QApplication.translate("FieldTool", "Load Walls to Window", None, QtGui.QApplication.UnicodeUTF8))
        self.postGenWalls.setText(QtGui.QApplication.translate("FieldTool", "Post-Gen Export", None, QtGui.QApplication.UnicodeUTF8))
        self.generateButton.setText(QtGui.QApplication.translate("FieldTool", "Generate", None, QtGui.QApplication.UnicodeUTF8))
        self.importButton.setText(QtGui.QApplication.translate("FieldTool", "Import To Maya", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("FieldTool", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit.setPlaceholderText(QtGui.QApplication.translate("FieldTool", "Cache Location", None, QtGui.QApplication.UnicodeUTF8))
        self.loadSettingsButton.setText(QtGui.QApplication.translate("FieldTool", "Load Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_2.setPlaceholderText(QtGui.QApplication.translate("FieldTool", "Cache Save Location", None, QtGui.QApplication.UnicodeUTF8))
        self.saveSettingsButton.setText(QtGui.QApplication.translate("FieldTool", "Save Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.resetSettingsButton.setText(QtGui.QApplication.translate("FieldTool", "Reset Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("FieldTool", "Save", None, QtGui.QApplication.UnicodeUTF8))