# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'importUI.ui'
#
# Created: Wed Jun 07 13:40:15 2017
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 264)
        self.widget = QtGui.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(10, 11, 381, 241))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.terrainBox = QtGui.QGroupBox(self.widget)
        self.terrainBox.setCheckable(True)
        self.terrainBox.setObjectName("terrainBox")
        self.widget1 = QtGui.QWidget(self.terrainBox)
        self.widget1.setGeometry(QtCore.QRect(10, 20, 361, 35))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.terrainLine = QtGui.QLineEdit(self.widget1)
        self.terrainLine.setObjectName("terrainLine")
        self.horizontalLayout.addWidget(self.terrainLine)
        self.terrainButton = QtGui.QPushButton(self.widget1)
        self.terrainButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Uni/FMP/Terrain/ui/browseFolder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.terrainButton.setIcon(icon)
        self.terrainButton.setIconSize(QtCore.QSize(25, 25))
        self.terrainButton.setFlat(True)
        self.terrainButton.setObjectName("terrainButton")
        self.horizontalLayout.addWidget(self.terrainButton)
        self.verticalLayout.addWidget(self.terrainBox)
        self.heightmapBox = QtGui.QGroupBox(self.widget)
        self.heightmapBox.setCheckable(True)
        self.heightmapBox.setChecked(False)
        self.heightmapBox.setObjectName("heightmapBox")
        self.layoutWidget = QtGui.QWidget(self.heightmapBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 361, 35))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.heightmapLine = QtGui.QLineEdit(self.layoutWidget)
        self.heightmapLine.setObjectName("heightmapLine")
        self.horizontalLayout_2.addWidget(self.heightmapLine)
        self.heightmapButton = QtGui.QPushButton(self.layoutWidget)
        self.heightmapButton.setText("")
        self.heightmapButton.setIcon(icon)
        self.heightmapButton.setIconSize(QtCore.QSize(25, 25))
        self.heightmapButton.setFlat(True)
        self.heightmapButton.setObjectName("heightmapButton")
        self.horizontalLayout_2.addWidget(self.heightmapButton)
        self.verticalLayout.addWidget(self.heightmapBox)
        self.textureBox = QtGui.QGroupBox(self.widget)
        self.textureBox.setCheckable(True)
        self.textureBox.setChecked(False)
        self.textureBox.setObjectName("textureBox")
        self.layoutWidget_2 = QtGui.QWidget(self.textureBox)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 20, 361, 35))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.textureLine = QtGui.QLineEdit(self.layoutWidget_2)
        self.textureLine.setObjectName("textureLine")
        self.horizontalLayout_3.addWidget(self.textureLine)
        self.textureButton = QtGui.QPushButton(self.layoutWidget_2)
        self.textureButton.setText("")
        self.textureButton.setIcon(icon)
        self.textureButton.setIconSize(QtCore.QSize(25, 25))
        self.textureButton.setFlat(True)
        self.textureButton.setObjectName("textureButton")
        self.horizontalLayout_3.addWidget(self.textureButton)
        self.verticalLayout.addWidget(self.textureBox)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.importButton = QtGui.QPushButton(self.widget)
        self.importButton.setObjectName("importButton")
        self.horizontalLayout_4.addWidget(self.importButton)
        self.cancelButton = QtGui.QPushButton(self.widget)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_4.addWidget(self.cancelButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Import To Maya", None, QtGui.QApplication.UnicodeUTF8))
        self.terrainBox.setTitle(QtGui.QApplication.translate("Dialog", "Terrain", None, QtGui.QApplication.UnicodeUTF8))
        self.heightmapBox.setTitle(QtGui.QApplication.translate("Dialog", "Heightmap", None, QtGui.QApplication.UnicodeUTF8))
        self.textureBox.setTitle(QtGui.QApplication.translate("Dialog", "Load Texture", None, QtGui.QApplication.UnicodeUTF8))
        self.importButton.setText(QtGui.QApplication.translate("Dialog", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("Dialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

