# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'importUI.ui'
#
# Created: Fri Jun 09 11:01:45 2017
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(420, 470)
        Dialog.setMinimumSize(QtCore.QSize(420, 470))
        Dialog.setMaximumSize(QtCore.QSize(420, 470))
        self.widget = QtGui.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(10, 10, 400, 450))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(400, 450))
        self.widget.setMaximumSize(QtCore.QSize(400, 430))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.terrainBox = QtGui.QGroupBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.terrainBox.sizePolicy().hasHeightForWidth())
        self.terrainBox.setSizePolicy(sizePolicy)
        self.terrainBox.setMinimumSize(QtCore.QSize(0, 60))
        self.terrainBox.setMaximumSize(QtCore.QSize(16777215, 60))
        self.terrainBox.setCheckable(True)
        self.terrainBox.setObjectName("terrainBox")
        self.layoutWidget = QtGui.QWidget(self.terrainBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 381, 35))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.terrainLine = QtGui.QLineEdit(self.layoutWidget)
        self.terrainLine.setObjectName("terrainLine")
        self.horizontalLayout.addWidget(self.terrainLine)
        self.terrainButton = QtGui.QPushButton(self.layoutWidget)
        self.terrainButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Uni/FMP/Terrain/ui/browseFolder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.terrainButton.setIcon(icon)
        self.terrainButton.setIconSize(QtCore.QSize(25, 25))
        self.terrainButton.setFlat(True)
        self.terrainButton.setObjectName("terrainButton")
        self.horizontalLayout.addWidget(self.terrainButton)
        self.verticalLayout.addWidget(self.terrainBox)
        self.heightmapBox = QtGui.QGroupBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heightmapBox.sizePolicy().hasHeightForWidth())
        self.heightmapBox.setSizePolicy(sizePolicy)
        self.heightmapBox.setMinimumSize(QtCore.QSize(0, 60))
        self.heightmapBox.setMaximumSize(QtCore.QSize(16777215, 60))
        self.heightmapBox.setCheckable(True)
        self.heightmapBox.setChecked(False)
        self.heightmapBox.setObjectName("heightmapBox")
        self.layoutWidget1 = QtGui.QWidget(self.heightmapBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 381, 35))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.heightmapLine = QtGui.QLineEdit(self.layoutWidget1)
        self.heightmapLine.setObjectName("heightmapLine")
        self.horizontalLayout_2.addWidget(self.heightmapLine)
        self.heightmapButton = QtGui.QPushButton(self.layoutWidget1)
        self.heightmapButton.setText("")
        self.heightmapButton.setIcon(icon)
        self.heightmapButton.setIconSize(QtCore.QSize(25, 25))
        self.heightmapButton.setFlat(True)
        self.heightmapButton.setObjectName("heightmapButton")
        self.horizontalLayout_2.addWidget(self.heightmapButton)
        self.verticalLayout.addWidget(self.heightmapBox)
        self.textureBox = QtGui.QGroupBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textureBox.sizePolicy().hasHeightForWidth())
        self.textureBox.setSizePolicy(sizePolicy)
        self.textureBox.setMinimumSize(QtCore.QSize(0, 60))
        self.textureBox.setMaximumSize(QtCore.QSize(16777215, 60))
        self.textureBox.setCheckable(True)
        self.textureBox.setChecked(False)
        self.textureBox.setObjectName("textureBox")
        self.layoutWidget_2 = QtGui.QWidget(self.textureBox)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 20, 381, 35))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.textureLine = QtGui.QLineEdit(self.layoutWidget_2)
        self.textureLine.setObjectName("textureLine")
        self.horizontalLayout_3.addWidget(self.textureLine)
        self.textureButton = QtGui.QPushButton(self.layoutWidget_2)
        self.textureButton.setText("")
        self.textureButton.setIcon(icon)
        self.textureButton.setIconSize(QtCore.QSize(25, 25))
        self.textureButton.setFlat(True)
        self.textureButton.setObjectName("textureButton")
        self.horizontalLayout_3.addWidget(self.textureButton)
        self.verticalLayout.addWidget(self.textureBox)
        self.wallsBox = QtGui.QGroupBox(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(200)
        sizePolicy.setHeightForWidth(self.wallsBox.sizePolicy().hasHeightForWidth())
        self.wallsBox.setSizePolicy(sizePolicy)
        self.wallsBox.setMinimumSize(QtCore.QSize(0, 150))
        self.wallsBox.setMaximumSize(QtCore.QSize(16777215, 200))
        self.wallsBox.setCheckable(True)
        self.wallsBox.setChecked(False)
        self.wallsBox.setObjectName("wallsBox")
        self.widget1 = QtGui.QWidget(self.wallsBox)
        self.widget1.setGeometry(QtCore.QRect(10, 20, 381, 171))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.wallsLine = QtGui.QLineEdit(self.widget1)
        self.wallsLine.setObjectName("wallsLine")
        self.horizontalLayout_5.addWidget(self.wallsLine)
        self.wallsButton = QtGui.QPushButton(self.widget1)
        self.wallsButton.setText("")
        self.wallsButton.setIcon(icon)
        self.wallsButton.setIconSize(QtCore.QSize(25, 25))
        self.wallsButton.setFlat(True)
        self.wallsButton.setObjectName("wallsButton")
        self.horizontalLayout_5.addWidget(self.wallsButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.wallsEdit = QtGui.QPlainTextEdit(self.widget1)
        self.wallsEdit.setObjectName("wallsEdit")
        self.verticalLayout_2.addWidget(self.wallsEdit)
        self.verticalLayout.addWidget(self.wallsBox)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.importButton = QtGui.QPushButton(self.widget)
        self.importButton.setObjectName("importButton")
        self.horizontalLayout_4.addWidget(self.importButton)
        self.cancelButton = QtGui.QPushButton(self.widget)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_4.addWidget(self.cancelButton)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Import To Maya", None, QtGui.QApplication.UnicodeUTF8))
        self.terrainBox.setTitle(QtGui.QApplication.translate("Dialog", "Terrain", None, QtGui.QApplication.UnicodeUTF8))
        self.heightmapBox.setTitle(QtGui.QApplication.translate("Dialog", "Heightmap", None, QtGui.QApplication.UnicodeUTF8))
        self.textureBox.setTitle(QtGui.QApplication.translate("Dialog", "Load Texture", None, QtGui.QApplication.UnicodeUTF8))
        self.wallsBox.setTitle(QtGui.QApplication.translate("Dialog", "Load Walls", None, QtGui.QApplication.UnicodeUTF8))
        self.importButton.setText(QtGui.QApplication.translate("Dialog", "Import", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("Dialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

