# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pythonUI.ui'
#
# Created: Fri Jun 09 18:19:42 2017
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1100, 875)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(1100, 875))
        Dialog.setCursor(QtCore.Qt.ArrowCursor)
        Dialog.setMouseTracking(True)
        self.verticalLayout_8 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.vLayoutWidget = QtGui.QWidget(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vLayoutWidget.sizePolicy().hasHeightForWidth())
        self.vLayoutWidget.setSizePolicy(sizePolicy)
        self.vLayoutWidget.setMinimumSize(QtCore.QSize(1050, 800))
        self.vLayoutWidget.setObjectName("vLayoutWidget")
        self.widget = QtGui.QWidget(self.vLayoutWidget)
        self.widget.setGeometry(QtCore.QRect(10, 9, 1060, 837))
        self.widget.setMinimumSize(QtCore.QSize(0, 800))
        self.widget.setObjectName("widget")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.imageLayout = QtGui.QWidget(self.widget)
        self.imageLayout.setMinimumSize(QtCore.QSize(0, 775))
        self.imageLayout.setObjectName("imageLayout")
        self.verticalLayout = QtGui.QVBoxLayout(self.imageLayout)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topLayoutWidget = QtGui.QWidget(self.imageLayout)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.topLayoutWidget.sizePolicy().hasHeightForWidth())
        self.topLayoutWidget.setSizePolicy(sizePolicy)
        self.topLayoutWidget.setMinimumSize(QtCore.QSize(700, 50))
        self.topLayoutWidget.setObjectName("topLayoutWidget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.topLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit = QtGui.QLineEdit(self.topLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.pushButton = QtGui.QPushButton(self.topLayoutWidget)
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../Uni/FMP/Terrain/ui/browseFolder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(25, 25))
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.loadSettingsButton = QtGui.QPushButton(self.topLayoutWidget)
        self.loadSettingsButton.setEnabled(True)
        self.loadSettingsButton.setObjectName("loadSettingsButton")
        self.horizontalLayout_2.addWidget(self.loadSettingsButton)
        spacerItem = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.resetSettingsButton = QtGui.QPushButton(self.topLayoutWidget)
        self.resetSettingsButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resetSettingsButton.sizePolicy().hasHeightForWidth())
        self.resetSettingsButton.setSizePolicy(sizePolicy)
        self.resetSettingsButton.setAutoFillBackground(False)
        self.resetSettingsButton.setAutoDefault(True)
        self.resetSettingsButton.setDefault(False)
        self.resetSettingsButton.setFlat(False)
        self.resetSettingsButton.setObjectName("resetSettingsButton")
        self.horizontalLayout_2.addWidget(self.resetSettingsButton)
        spacerItem1 = QtGui.QSpacerItem(50, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.lineEdit_2 = QtGui.QLineEdit(self.topLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.pushButton_2 = QtGui.QPushButton(self.topLayoutWidget)
        self.pushButton_2.setText("")
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.saveSettingsButton = QtGui.QPushButton(self.topLayoutWidget)
        self.saveSettingsButton.setEnabled(False)
        self.saveSettingsButton.setObjectName("saveSettingsButton")
        self.horizontalLayout_2.addWidget(self.saveSettingsButton)
        self.verticalLayout.addWidget(self.topLayoutWidget)
        self.imageButton = QtGui.QPushButton(self.imageLayout)
        self.imageButton.setEnabled(False)
        self.imageButton.setMinimumSize(QtCore.QSize(720, 720))
        self.imageButton.setMaximumSize(QtCore.QSize(720, 720))
        self.imageButton.setCursor(QtCore.Qt.CrossCursor)
        self.imageButton.setAutoFillBackground(True)
        self.imageButton.setText("")
        self.imageButton.setIconSize(QtCore.QSize(720, 720))
        self.imageButton.setCheckable(False)
        self.imageButton.setAutoDefault(False)
        self.imageButton.setFlat(False)
        self.imageButton.setObjectName("imageButton")
        self.verticalLayout.addWidget(self.imageButton)
        self.bottomLayoutWidget = QtGui.QWidget(self.imageLayout)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bottomLayoutWidget.sizePolicy().hasHeightForWidth())
        self.bottomLayoutWidget.setSizePolicy(sizePolicy)
        self.bottomLayoutWidget.setMinimumSize(QtCore.QSize(700, 50))
        self.bottomLayoutWidget.setObjectName("bottomLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.bottomLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtGui.QSpacerItem(78, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.switch3DButton = QtGui.QPushButton(self.bottomLayoutWidget)
        self.switch3DButton.setEnabled(False)
        self.switch3DButton.setObjectName("switch3DButton")
        self.horizontalLayout.addWidget(self.switch3DButton)
        spacerItem3 = QtGui.QSpacerItem(78, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addWidget(self.bottomLayoutWidget)
        self.slider3D = QtGui.QSlider(self.imageLayout)
        self.slider3D.setMaximum(20)
        self.slider3D.setProperty("value", 10)
        self.slider3D.setOrientation(QtCore.Qt.Horizontal)
        self.slider3D.setInvertedAppearance(False)
        self.slider3D.setObjectName("slider3D")
        self.verticalLayout.addWidget(self.slider3D)
        self.horizontalLayout_6.addWidget(self.imageLayout)
        self.tabWidget = QtGui.QTabWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(325, 775))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 900))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.top = QtGui.QWidget(self.tab)
        self.top.setGeometry(QtCore.QRect(10, 10, 301, 730))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.top.sizePolicy().hasHeightForWidth())
        self.top.setSizePolicy(sizePolicy)
        self.top.setMinimumSize(QtCore.QSize(300, 730))
        self.top.setMaximumSize(QtCore.QSize(16777215, 900))
        self.top.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.top.setObjectName("top")
        self.layoutWidget = QtGui.QWidget(self.top)
        self.layoutWidget.setGeometry(QtCore.QRect(9, 10, 283, 714))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Settings = QtGui.QFrame(self.layoutWidget)
        self.Settings.setMinimumSize(QtCore.QSize(200, 0))
        self.Settings.setFrameShape(QtGui.QFrame.StyledPanel)
        self.Settings.setFrameShadow(QtGui.QFrame.Plain)
        self.Settings.setObjectName("Settings")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.Settings)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.seedValueCheck = QtGui.QCheckBox(self.Settings)
        self.seedValueCheck.setMinimumSize(QtCore.QSize(0, 0))
        self.seedValueCheck.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.seedValueCheck.setIconSize(QtCore.QSize(16, 16))
        self.seedValueCheck.setObjectName("seedValueCheck")
        self.horizontalLayout_3.addWidget(self.seedValueCheck)
        self.seedValueBox = QtGui.QSpinBox(self.Settings)
        self.seedValueBox.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seedValueBox.sizePolicy().hasHeightForWidth())
        self.seedValueBox.setSizePolicy(sizePolicy)
        self.seedValueBox.setMinimumSize(QtCore.QSize(50, 0))
        self.seedValueBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.seedValueBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.seedValueBox.setMaximum(999999999)
        self.seedValueBox.setObjectName("seedValueBox")
        self.horizontalLayout_3.addWidget(self.seedValueBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtGui.QLabel(self.Settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.terrainSizeBox = QtGui.QSpinBox(self.Settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.terrainSizeBox.sizePolicy().hasHeightForWidth())
        self.terrainSizeBox.setSizePolicy(sizePolicy)
        self.terrainSizeBox.setMinimumSize(QtCore.QSize(100, 0))
        self.terrainSizeBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.terrainSizeBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.terrainSizeBox.setMinimum(1)
        self.terrainSizeBox.setMaximum(100)
        self.terrainSizeBox.setProperty("value", 50)
        self.terrainSizeBox.setObjectName("terrainSizeBox")
        self.horizontalLayout_5.addWidget(self.terrainSizeBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtGui.QLabel(self.Settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.startPointSizeBox = QtGui.QSpinBox(self.Settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startPointSizeBox.sizePolicy().hasHeightForWidth())
        self.startPointSizeBox.setSizePolicy(sizePolicy)
        self.startPointSizeBox.setMinimumSize(QtCore.QSize(100, 0))
        self.startPointSizeBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.startPointSizeBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.startPointSizeBox.setMinimum(1)
        self.startPointSizeBox.setMaximum(100)
        self.startPointSizeBox.setProperty("value", 6)
        self.startPointSizeBox.setObjectName("startPointSizeBox")
        self.horizontalLayout_4.addWidget(self.startPointSizeBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_5 = QtGui.QLabel(self.Settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(100, 0))
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_8.addWidget(self.label_5)
        self.roughnessBox = QtGui.QDoubleSpinBox(self.Settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.roughnessBox.sizePolicy().hasHeightForWidth())
        self.roughnessBox.setSizePolicy(sizePolicy)
        self.roughnessBox.setMinimumSize(QtCore.QSize(100, 0))
        self.roughnessBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.roughnessBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.roughnessBox.setDecimals(3)
        self.roughnessBox.setSingleStep(0.1)
        self.roughnessBox.setProperty("value", 12.0)
        self.roughnessBox.setObjectName("roughnessBox")
        self.horizontalLayout_8.addWidget(self.roughnessBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_6 = QtGui.QLabel(self.Settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(100, 0))
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        self.heightmapIterationsBox = QtGui.QSpinBox(self.Settings)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heightmapIterationsBox.sizePolicy().hasHeightForWidth())
        self.heightmapIterationsBox.setSizePolicy(sizePolicy)
        self.heightmapIterationsBox.setMinimumSize(QtCore.QSize(100, 0))
        self.heightmapIterationsBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.heightmapIterationsBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.heightmapIterationsBox.setMinimum(1)
        self.heightmapIterationsBox.setProperty("value", 6)
        self.heightmapIterationsBox.setObjectName("heightmapIterationsBox")
        self.horizontalLayout_9.addWidget(self.heightmapIterationsBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.verticalLayout_3.addWidget(self.Settings)
        self.farmPosition = QtGui.QGroupBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.farmPosition.sizePolicy().hasHeightForWidth())
        self.farmPosition.setSizePolicy(sizePolicy)
        self.farmPosition.setMinimumSize(QtCore.QSize(200, 0))
        self.farmPosition.setMaximumSize(QtCore.QSize(16777215, 300))
        self.farmPosition.setCheckable(True)
        self.farmPosition.setChecked(False)
        self.farmPosition.setObjectName("farmPosition")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.farmPosition)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.farmTranslateLayout = QtGui.QWidget(self.farmPosition)
        self.farmTranslateLayout.setMinimumSize(QtCore.QSize(0, 30))
        self.farmTranslateLayout.setMaximumSize(QtCore.QSize(16777215, 30))
        self.farmTranslateLayout.setObjectName("farmTranslateLayout")
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.farmTranslateLayout)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_7 = QtGui.QLabel(self.farmTranslateLayout)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMinimumSize(QtCore.QSize(50, 0))
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_10.addWidget(self.label_7)
        self.translateXBox = QtGui.QDoubleSpinBox(self.farmTranslateLayout)
        self.translateXBox.setMinimumSize(QtCore.QSize(48, 0))
        self.translateXBox.setFrame(True)
        self.translateXBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.translateXBox.setDecimals(3)
        self.translateXBox.setMinimum(-99.99)
        self.translateXBox.setObjectName("translateXBox")
        self.horizontalLayout_10.addWidget(self.translateXBox)
        self.translateYBox = QtGui.QDoubleSpinBox(self.farmTranslateLayout)
        self.translateYBox.setMinimumSize(QtCore.QSize(48, 0))
        self.translateYBox.setFrame(True)
        self.translateYBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.translateYBox.setDecimals(3)
        self.translateYBox.setMinimum(-99.9)
        self.translateYBox.setObjectName("translateYBox")
        self.horizontalLayout_10.addWidget(self.translateYBox)
        self.translateZBox = QtGui.QDoubleSpinBox(self.farmTranslateLayout)
        self.translateZBox.setMinimumSize(QtCore.QSize(48, 0))
        self.translateZBox.setFrame(True)
        self.translateZBox.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.translateZBox.setDecimals(3)
        self.translateZBox.setMinimum(-99.99)
        self.translateZBox.setObjectName("translateZBox")
        self.horizontalLayout_10.addWidget(self.translateZBox)
        self.verticalLayout_4.addWidget(self.farmTranslateLayout)
        self.farmMeshLayout = QtGui.QWidget(self.farmPosition)
        self.farmMeshLayout.setMinimumSize(QtCore.QSize(0, 35))
        self.farmMeshLayout.setMaximumSize(QtCore.QSize(16777215, 35))
        self.farmMeshLayout.setObjectName("farmMeshLayout")
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.farmMeshLayout)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_8 = QtGui.QLabel(self.farmMeshLayout)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMinimumSize(QtCore.QSize(10, 0))
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_11.addWidget(self.label_8)
        self.farmMeshLine = QtGui.QLineEdit(self.farmMeshLayout)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.farmMeshLine.sizePolicy().hasHeightForWidth())
        self.farmMeshLine.setSizePolicy(sizePolicy)
        self.farmMeshLine.setMinimumSize(QtCore.QSize(100, 0))
        self.farmMeshLine.setObjectName("farmMeshLine")
        self.horizontalLayout_11.addWidget(self.farmMeshLine)
        self.farmMeshButton = QtGui.QPushButton(self.farmMeshLayout)
        self.farmMeshButton.setMinimumSize(QtCore.QSize(10, 0))
        self.farmMeshButton.setText("")
        self.farmMeshButton.setIcon(icon)
        self.farmMeshButton.setIconSize(QtCore.QSize(25, 25))
        self.farmMeshButton.setCheckable(False)
        self.farmMeshButton.setAutoDefault(False)
        self.farmMeshButton.setDefault(False)
        self.farmMeshButton.setFlat(True)
        self.farmMeshButton.setObjectName("farmMeshButton")
        self.horizontalLayout_11.addWidget(self.farmMeshButton)
        self.verticalLayout_4.addWidget(self.farmMeshLayout)
        self.farmMeshBrowser = QtGui.QPlainTextEdit(self.farmPosition)
        self.farmMeshBrowser.setReadOnly(True)
        self.farmMeshBrowser.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.farmMeshBrowser.setObjectName("farmMeshBrowser")
        self.verticalLayout_4.addWidget(self.farmMeshBrowser)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout_3.addWidget(self.farmPosition)
        self.trees = QtGui.QGroupBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.trees.sizePolicy().hasHeightForWidth())
        self.trees.setSizePolicy(sizePolicy)
        self.trees.setMinimumSize(QtCore.QSize(0, 200))
        self.trees.setMaximumSize(QtCore.QSize(16777215, 300))
        self.trees.setCheckable(True)
        self.trees.setChecked(False)
        self.trees.setObjectName("trees")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.trees)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.clusterTreesLayout = QtGui.QWidget(self.trees)
        self.clusterTreesLayout.setMaximumSize(QtCore.QSize(16777215, 30))
        self.clusterTreesLayout.setObjectName("clusterTreesLayout")
        self.horizontalLayout_13 = QtGui.QHBoxLayout(self.clusterTreesLayout)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.normalTreesCheck = QtGui.QCheckBox(self.clusterTreesLayout)
        self.normalTreesCheck.setChecked(True)
        self.normalTreesCheck.setObjectName("normalTreesCheck")
        self.horizontalLayout_13.addWidget(self.normalTreesCheck)
        self.clusterTreesCheck = QtGui.QCheckBox(self.clusterTreesLayout)
        self.clusterTreesCheck.setMinimumSize(QtCore.QSize(0, 20))
        self.clusterTreesCheck.setChecked(True)
        self.clusterTreesCheck.setObjectName("clusterTreesCheck")
        self.horizontalLayout_13.addWidget(self.clusterTreesCheck)
        self.verticalLayout_7.addWidget(self.clusterTreesLayout)
        self.TreeMeshLayout = QtGui.QWidget(self.trees)
        self.TreeMeshLayout.setMinimumSize(QtCore.QSize(0, 35))
        self.TreeMeshLayout.setMaximumSize(QtCore.QSize(16777215, 35))
        self.TreeMeshLayout.setObjectName("TreeMeshLayout")
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.TreeMeshLayout)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_9 = QtGui.QLabel(self.TreeMeshLayout)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMinimumSize(QtCore.QSize(10, 0))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_12.addWidget(self.label_9)
        self.treeMeshLine = QtGui.QLineEdit(self.TreeMeshLayout)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeMeshLine.sizePolicy().hasHeightForWidth())
        self.treeMeshLine.setSizePolicy(sizePolicy)
        self.treeMeshLine.setMinimumSize(QtCore.QSize(100, 0))
        self.treeMeshLine.setObjectName("treeMeshLine")
        self.horizontalLayout_12.addWidget(self.treeMeshLine)
        self.treeMeshButton = QtGui.QPushButton(self.TreeMeshLayout)
        self.treeMeshButton.setMinimumSize(QtCore.QSize(10, 0))
        self.treeMeshButton.setText("")
        self.treeMeshButton.setIcon(icon)
        self.treeMeshButton.setIconSize(QtCore.QSize(25, 25))
        self.treeMeshButton.setCheckable(False)
        self.treeMeshButton.setAutoDefault(False)
        self.treeMeshButton.setDefault(False)
        self.treeMeshButton.setFlat(True)
        self.treeMeshButton.setObjectName("treeMeshButton")
        self.horizontalLayout_12.addWidget(self.treeMeshButton)
        self.verticalLayout_7.addWidget(self.TreeMeshLayout)
        self.treeMeshBrowser = QtGui.QPlainTextEdit(self.trees)
        self.treeMeshBrowser.setReadOnly(True)
        self.treeMeshBrowser.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.treeMeshBrowser.setObjectName("treeMeshBrowser")
        self.verticalLayout_7.addWidget(self.treeMeshBrowser)
        self.verticalLayout_3.addWidget(self.trees)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.layoutWidget1 = QtGui.QWidget(self.tab_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 306, 791))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label = QtGui.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.horizontalLayout_23.addWidget(self.label)
        self.defaultLine = QtGui.QLineEdit(self.layoutWidget1)
        self.defaultLine.setObjectName("defaultLine")
        self.horizontalLayout_23.addWidget(self.defaultLine)
        self.defaultButton = QtGui.QPushButton(self.layoutWidget1)
        self.defaultButton.setText("")
        self.defaultButton.setIcon(icon)
        self.defaultButton.setIconSize(QtCore.QSize(25, 25))
        self.defaultButton.setFlat(True)
        self.defaultButton.setObjectName("defaultButton")
        self.horizontalLayout_23.addWidget(self.defaultButton)
        self.verticalLayout_14.addLayout(self.horizontalLayout_23)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox = QtGui.QGroupBox(self.layoutWidget1)
        self.groupBox.setEnabled(True)
        self.groupBox.setMinimumSize(QtCore.QSize(300, 90))
        self.groupBox.setMaximumSize(QtCore.QSize(300, 90))
        self.groupBox.setCheckable(True)
        self.groupBox.setChecked(False)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget2 = QtGui.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(11, 21, 281, 68))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_10 = QtGui.QLabel(self.layoutWidget2)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.terrainLine = QtGui.QLineEdit(self.layoutWidget2)
        self.terrainLine.setObjectName("terrainLine")
        self.horizontalLayout_7.addWidget(self.terrainLine)
        self.terrainButton = QtGui.QPushButton(self.layoutWidget2)
        self.terrainButton.setText("")
        self.terrainButton.setIcon(icon)
        self.terrainButton.setIconSize(QtCore.QSize(25, 25))
        self.terrainButton.setFlat(True)
        self.terrainButton.setObjectName("terrainButton")
        self.horizontalLayout_7.addWidget(self.terrainButton)
        self.verticalLayout_15.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.triangulateCheck = QtGui.QCheckBox(self.layoutWidget2)
        self.triangulateCheck.setObjectName("triangulateCheck")
        self.horizontalLayout_24.addWidget(self.triangulateCheck)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem4)
        self.postGenTerrain = QtGui.QPushButton(self.layoutWidget2)
        self.postGenTerrain.setEnabled(False)
        self.postGenTerrain.setObjectName("postGenTerrain")
        self.horizontalLayout_24.addWidget(self.postGenTerrain)
        self.verticalLayout_15.addLayout(self.horizontalLayout_24)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.layoutWidget1)
        self.groupBox_2.setMinimumSize(QtCore.QSize(300, 120))
        self.groupBox_2.setMaximumSize(QtCore.QSize(300, 120))
        self.groupBox_2.setCheckable(True)
        self.groupBox_2.setChecked(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget3 = QtGui.QWidget(self.groupBox_2)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 26, 281, 81))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.TextureLayout = QtGui.QWidget(self.layoutWidget3)
        self.TextureLayout.setMinimumSize(QtCore.QSize(0, 30))
        self.TextureLayout.setMaximumSize(QtCore.QSize(16777215, 20))
        self.TextureLayout.setObjectName("TextureLayout")
        self.horizontalLayout_14 = QtGui.QHBoxLayout(self.TextureLayout)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_11 = QtGui.QLabel(self.TextureLayout)
        self.label_11.setMinimumSize(QtCore.QSize(0, 20))
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_14.addWidget(self.label_11)
        self.textureLine = QtGui.QLineEdit(self.TextureLayout)
        self.textureLine.setMinimumSize(QtCore.QSize(0, 20))
        self.textureLine.setMaximumSize(QtCore.QSize(16777215, 20))
        self.textureLine.setObjectName("textureLine")
        self.horizontalLayout_14.addWidget(self.textureLine)
        self.textureButton = QtGui.QPushButton(self.TextureLayout)
        self.textureButton.setMinimumSize(QtCore.QSize(0, 20))
        self.textureButton.setMaximumSize(QtCore.QSize(16777215, 20))
        self.textureButton.setText("")
        self.textureButton.setIcon(icon)
        self.textureButton.setIconSize(QtCore.QSize(25, 25))
        self.textureButton.setFlat(True)
        self.textureButton.setObjectName("textureButton")
        self.horizontalLayout_14.addWidget(self.textureButton)
        self.verticalLayout_9.addWidget(self.TextureLayout)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem5)
        self.loadTextureButton = QtGui.QPushButton(self.layoutWidget3)
        self.loadTextureButton.setEnabled(False)
        self.loadTextureButton.setObjectName("loadTextureButton")
        self.horizontalLayout_20.addWidget(self.loadTextureButton)
        self.postGenTexture = QtGui.QPushButton(self.layoutWidget3)
        self.postGenTexture.setEnabled(False)
        self.postGenTexture.setObjectName("postGenTexture")
        self.horizontalLayout_20.addWidget(self.postGenTexture)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem6)
        self.verticalLayout_9.addLayout(self.horizontalLayout_20)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.layoutWidget1)
        self.groupBox_3.setMinimumSize(QtCore.QSize(300, 120))
        self.groupBox_3.setMaximumSize(QtCore.QSize(300, 120))
        self.groupBox_3.setCheckable(True)
        self.groupBox_3.setChecked(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget4 = QtGui.QWidget(self.groupBox_3)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 20, 281, 81))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.TextureLayout_2 = QtGui.QWidget(self.layoutWidget4)
        self.TextureLayout_2.setMinimumSize(QtCore.QSize(0, 30))
        self.TextureLayout_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.TextureLayout_2.setObjectName("TextureLayout_2")
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.TextureLayout_2)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_12 = QtGui.QLabel(self.TextureLayout_2)
        self.label_12.setMinimumSize(QtCore.QSize(0, 20))
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_15.addWidget(self.label_12)
        self.heightmapLine = QtGui.QLineEdit(self.TextureLayout_2)
        self.heightmapLine.setMinimumSize(QtCore.QSize(0, 20))
        self.heightmapLine.setMaximumSize(QtCore.QSize(16777215, 20))
        self.heightmapLine.setObjectName("heightmapLine")
        self.horizontalLayout_15.addWidget(self.heightmapLine)
        self.heightmapButton = QtGui.QPushButton(self.TextureLayout_2)
        self.heightmapButton.setMinimumSize(QtCore.QSize(0, 20))
        self.heightmapButton.setMaximumSize(QtCore.QSize(16777215, 20))
        self.heightmapButton.setText("")
        self.heightmapButton.setIcon(icon)
        self.heightmapButton.setIconSize(QtCore.QSize(25, 25))
        self.heightmapButton.setFlat(True)
        self.heightmapButton.setObjectName("heightmapButton")
        self.horizontalLayout_15.addWidget(self.heightmapButton)
        self.verticalLayout_12.addWidget(self.TextureLayout_2)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem7)
        self.loadHeightmapButton = QtGui.QPushButton(self.layoutWidget4)
        self.loadHeightmapButton.setEnabled(False)
        self.loadHeightmapButton.setObjectName("loadHeightmapButton")
        self.horizontalLayout_22.addWidget(self.loadHeightmapButton)
        self.postGenHeightmap = QtGui.QPushButton(self.layoutWidget4)
        self.postGenHeightmap.setEnabled(False)
        self.postGenHeightmap.setObjectName("postGenHeightmap")
        self.horizontalLayout_22.addWidget(self.postGenHeightmap)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem8)
        self.verticalLayout_12.addLayout(self.horizontalLayout_22)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.layoutWidget1)
        self.groupBox_4.setMinimumSize(QtCore.QSize(300, 120))
        self.groupBox_4.setMaximumSize(QtCore.QSize(300, 120))
        self.groupBox_4.setCheckable(True)
        self.groupBox_4.setChecked(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.layoutWidget5 = QtGui.QWidget(self.groupBox_4)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 20, 281, 81))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.TextureLayout_3 = QtGui.QWidget(self.layoutWidget5)
        self.TextureLayout_3.setMinimumSize(QtCore.QSize(0, 30))
        self.TextureLayout_3.setMaximumSize(QtCore.QSize(16777215, 20))
        self.TextureLayout_3.setObjectName("TextureLayout_3")
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.TextureLayout_3)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_13 = QtGui.QLabel(self.TextureLayout_3)
        self.label_13.setMinimumSize(QtCore.QSize(0, 20))
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_16.addWidget(self.label_13)
        self.wallsLine = QtGui.QLineEdit(self.TextureLayout_3)
        self.wallsLine.setMinimumSize(QtCore.QSize(0, 20))
        self.wallsLine.setMaximumSize(QtCore.QSize(16777215, 20))
        self.wallsLine.setObjectName("wallsLine")
        self.horizontalLayout_16.addWidget(self.wallsLine)
        self.wallsButton = QtGui.QPushButton(self.TextureLayout_3)
        self.wallsButton.setMinimumSize(QtCore.QSize(0, 20))
        self.wallsButton.setMaximumSize(QtCore.QSize(16777215, 20))
        self.wallsButton.setText("")
        self.wallsButton.setIcon(icon)
        self.wallsButton.setIconSize(QtCore.QSize(25, 25))
        self.wallsButton.setFlat(True)
        self.wallsButton.setObjectName("wallsButton")
        self.horizontalLayout_16.addWidget(self.wallsButton)
        self.verticalLayout_10.addWidget(self.TextureLayout_3)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem9)
        self.loadWallsButton = QtGui.QPushButton(self.layoutWidget5)
        self.loadWallsButton.setEnabled(False)
        self.loadWallsButton.setObjectName("loadWallsButton")
        self.horizontalLayout_21.addWidget(self.loadWallsButton)
        self.postGenWalls = QtGui.QPushButton(self.layoutWidget5)
        self.postGenWalls.setEnabled(False)
        self.postGenWalls.setObjectName("postGenWalls")
        self.horizontalLayout_21.addWidget(self.postGenWalls)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem10)
        self.verticalLayout_10.addLayout(self.horizontalLayout_21)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        self.groupBox_5 = QtGui.QGroupBox(self.layoutWidget1)
        self.groupBox_5.setEnabled(False)
        self.groupBox_5.setMinimumSize(QtCore.QSize(300, 60))
        self.groupBox_5.setMaximumSize(QtCore.QSize(300, 60))
        self.groupBox_5.setCheckable(True)
        self.groupBox_5.setChecked(False)
        self.groupBox_5.setObjectName("groupBox_5")
        self.TextureLayout_4 = QtGui.QWidget(self.groupBox_5)
        self.TextureLayout_4.setGeometry(QtCore.QRect(10, 20, 281, 30))
        self.TextureLayout_4.setMinimumSize(QtCore.QSize(0, 30))
        self.TextureLayout_4.setMaximumSize(QtCore.QSize(16777215, 20))
        self.TextureLayout_4.setObjectName("TextureLayout_4")
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.TextureLayout_4)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_14 = QtGui.QLabel(self.TextureLayout_4)
        self.label_14.setMinimumSize(QtCore.QSize(0, 20))
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_17.addWidget(self.label_14)
        self.locationLine = QtGui.QLineEdit(self.TextureLayout_4)
        self.locationLine.setMinimumSize(QtCore.QSize(0, 20))
        self.locationLine.setMaximumSize(QtCore.QSize(16777215, 20))
        self.locationLine.setObjectName("locationLine")
        self.horizontalLayout_17.addWidget(self.locationLine)
        self.locationButton = QtGui.QPushButton(self.TextureLayout_4)
        self.locationButton.setMinimumSize(QtCore.QSize(0, 20))
        self.locationButton.setMaximumSize(QtCore.QSize(16777215, 20))
        self.locationButton.setText("")
        self.locationButton.setIcon(icon)
        self.locationButton.setIconSize(QtCore.QSize(25, 25))
        self.locationButton.setFlat(True)
        self.locationButton.setObjectName("locationButton")
        self.horizontalLayout_17.addWidget(self.locationButton)
        self.verticalLayout_5.addWidget(self.groupBox_5)
        self.verticalLayout_13.addLayout(self.verticalLayout_5)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem11 = QtGui.QSpacerItem(58, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem11)
        self.generateButton = QtGui.QPushButton(self.layoutWidget1)
        self.generateButton.setMinimumSize(QtCore.QSize(75, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.generateButton.setFont(font)
        self.generateButton.setObjectName("generateButton")
        self.horizontalLayout_18.addWidget(self.generateButton)
        spacerItem12 = QtGui.QSpacerItem(58, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem12)
        self.verticalLayout_11.addLayout(self.horizontalLayout_18)
        self.generateProgress = QtGui.QProgressBar(self.layoutWidget1)
        self.generateProgress.setEnabled(False)
        self.generateProgress.setProperty("value", 0)
        self.generateProgress.setAlignment(QtCore.Qt.AlignCenter)
        self.generateProgress.setTextVisible(True)
        self.generateProgress.setObjectName("generateProgress")
        self.verticalLayout_11.addWidget(self.generateProgress)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem13 = QtGui.QSpacerItem(58, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem13)
        self.importButton = QtGui.QPushButton(self.layoutWidget1)
        self.importButton.setEnabled(False)
        self.importButton.setMinimumSize(QtCore.QSize(75, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.importButton.setFont(font)
        self.importButton.setObjectName("importButton")
        self.horizontalLayout_19.addWidget(self.importButton)
        spacerItem14 = QtGui.QSpacerItem(58, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem14)
        self.verticalLayout_11.addLayout(self.horizontalLayout_19)
        self.importProgress = QtGui.QProgressBar(self.layoutWidget1)
        self.importProgress.setEnabled(False)
        self.importProgress.setProperty("value", 0)
        self.importProgress.setTextVisible(False)
        self.importProgress.setObjectName("importProgress")
        self.verticalLayout_11.addWidget(self.importProgress)
        self.verticalLayout_13.addLayout(self.verticalLayout_11)
        self.verticalLayout_14.addLayout(self.verticalLayout_13)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_6.addWidget(self.tabWidget)
        self.verticalLayout_8.addWidget(self.vLayoutWidget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.seedValueCheck, QtCore.SIGNAL("toggled(bool)"), self.seedValueBox.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Field Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit.setPlaceholderText(QtGui.QApplication.translate("Dialog", "Cache Location", None, QtGui.QApplication.UnicodeUTF8))
        self.loadSettingsButton.setText(QtGui.QApplication.translate("Dialog", "Load Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.resetSettingsButton.setText(QtGui.QApplication.translate("Dialog", "Reset Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_2.setPlaceholderText(QtGui.QApplication.translate("Dialog", "Cache Save Location", None, QtGui.QApplication.UnicodeUTF8))
        self.saveSettingsButton.setText(QtGui.QApplication.translate("Dialog", "Save Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.switch3DButton.setText(QtGui.QApplication.translate("Dialog", "Switch to 3D", None, QtGui.QApplication.UnicodeUTF8))
        self.seedValueCheck.setText(QtGui.QApplication.translate("Dialog", "Seed Value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Terrain Size", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Start Point Size", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Roughness Value", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Heightmap Iterations", None, QtGui.QApplication.UnicodeUTF8))
        self.farmPosition.setTitle(QtGui.QApplication.translate("Dialog", "Farm Position", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Translate", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Farm Meshes", None, QtGui.QApplication.UnicodeUTF8))
        self.trees.setTitle(QtGui.QApplication.translate("Dialog", "Trees", None, QtGui.QApplication.UnicodeUTF8))
        self.normalTreesCheck.setText(QtGui.QApplication.translate("Dialog", "Normal Trees", None, QtGui.QApplication.UnicodeUTF8))
        self.clusterTreesCheck.setText(QtGui.QApplication.translate("Dialog", "Cluster Trees", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Tree Meshes", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Dialog", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Set Default", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Export Terrain", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Export Location", None, QtGui.QApplication.UnicodeUTF8))
        self.triangulateCheck.setText(QtGui.QApplication.translate("Dialog", "Triangulate Mesh", None, QtGui.QApplication.UnicodeUTF8))
        self.postGenTerrain.setText(QtGui.QApplication.translate("Dialog", "Post-Gen Export", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Export Texture", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "Export Location", None, QtGui.QApplication.UnicodeUTF8))
        self.loadTextureButton.setText(QtGui.QApplication.translate("Dialog", "Load Texture to Window", None, QtGui.QApplication.UnicodeUTF8))
        self.postGenTexture.setText(QtGui.QApplication.translate("Dialog", "Post-Gen Export", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "Export Heightmap", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "Export Location", None, QtGui.QApplication.UnicodeUTF8))
        self.loadHeightmapButton.setText(QtGui.QApplication.translate("Dialog", "Load Heightmap to Window", None, QtGui.QApplication.UnicodeUTF8))
        self.postGenHeightmap.setText(QtGui.QApplication.translate("Dialog", "Post-Gen Export", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Dialog", "Export Walls", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "Export Location", None, QtGui.QApplication.UnicodeUTF8))
        self.loadWallsButton.setText(QtGui.QApplication.translate("Dialog", "Load Walls to Window", None, QtGui.QApplication.UnicodeUTF8))
        self.postGenWalls.setText(QtGui.QApplication.translate("Dialog", "Post-Gen Export", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Dialog", "Export Tree/Farm Position", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog", "Export Location", None, QtGui.QApplication.UnicodeUTF8))
        self.generateButton.setText(QtGui.QApplication.translate("Dialog", "Generate", None, QtGui.QApplication.UnicodeUTF8))
        self.importButton.setText(QtGui.QApplication.translate("Dialog", "Import To Maya", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Dialog", "Export", None, QtGui.QApplication.UnicodeUTF8))

